### ISSUE TITLE
Master sequence diagram for OAuth2 flow

### ISSUE THREAD

**Issue by Kenny2github** [ScratchVerifier/ScratchOAuth2#1]
- [x] Client registration: 1-5 - #4
- [x] User first visit to SOA2: 8-11 - #10
- [x] Login page and nonce: 15-22 - #11
- [x] Login submit and SOA2-Scratch interaction: 23-33 - #3
- [x] Start auth confirmation: 12-14 and 34-38 - #6
- [x] Submit auth confirmation: 39-42 - #5
- [x] Request access and refresh token: 45-56 - #7
- [x] Request access token via RT: 57-64 - #12
- [x] Request username: 66-68 - #13
![Master sequence diagram](https://cdn.discordapp.com/attachments/695071581998940231/780032309444608010/mermaid-diagram-20201122073000.png)
