### ISSUE TITLE
Master sequence diagram for MW SOA2 flow

### ISSUE THREAD

**Issue by Kenny2github** [ScratchVerifier/ScratchOAuth2#34]
Updates #1
- [x] Client registration: 1-5 - #36
- [x] Login page: 11-16 - #37
- [x] Login submit and SOA2-Scratch interaction: 17-24 - #38
- [x] Start auth: 8-10 and 25-29 - #39 (amendment: confirmation page includes hidden CSRF)
- [x] Finish auth: 30-33 - #40 (amendment: submitting sends and checks CSRF)
- [x] Request access (and refresh) token: 36-47 - #42
- [x] Request access (from refresh) token: 48-54 - #43
- [x] Request username from access token: 56-58 - #44

Amendment: The `access_tokens` table references `refresh_tokens` now, not the other way around.

![sequence diagram](https://cdn.discordapp.com/attachments/695071581998940231/810140649420095498/soa2_mermaid.png)
